spring:
  datasource:
    url: jdbc:mysql://192.168.0.106:3306/ebbinghaus?serverTimezone=UTC&characterEncoding=utf-8
    username: ebbinghaus
    password: ebbinghaus
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy